### ISSUE TITLE
Return appropriate error code for catalog validation errors

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill#1674]
Some of the catalog validation errors do not provide sufficient information about the actual error.  For example, if a user tries to upload a catalog twice, Kaui displays `Invalid catalog for tenant : 1`.  We should display a better error message. 

Related google group question - https://groups.google.com/g/killbilling-users/c/NdEDo8lvNvI

**Comment by FlowWriter** [comment]
Saw this when working on the "How to Pause/Resume a Subscription in Kaui." When you set a date to resume that is in the future, you see the confirmation message, "Bundle was successfully resumed." Well, that could be misinterpreted by the user, who would think it was resumed at that moment instead of on the future date.

**Comment by pierre** [comment]
From an implementation perspective, wondering if we shouldn't:

* Keep catalog upload as-is, i.e. return 400 error if a user uploads a bad catalog
* Make the catalog validation endpoint (https://github.com/killbill/killbill/pull/1746/files#diff-2c0bd5ecc3ffea40e59d169d5137732e7480bce04055856f285262fe4d229458R250) return a proper object with validation error details
