### ISSUE TITLE
Charged Through Date Not updating for FixedTerm phase with fixed one time charges in case of IN_ADVANCE billing

### ISSUE THREAD

**Issue by KBbitsP** [killbill/killbill#1739]
Current behavior : 

By definition, the chargedthroughdate is associated with recurring subscriptions, that is it specifies the date up to which a user has been billed for in case of a recurring subscription. Currently we do not support updating it in case of  FIXEDTERM plans.

Expected behavior : 

CTD should also be updated for a FIXEDTERM phase with fixed one time charges in case of IN_ADVANCE billing? Since the user has already been invoiced for the duration of the FIXEDTERM? Currently, the CTD is not updated in such scenarios.

**Comment by reshmabidikar** [comment]
**Work done so far (Code changes in the [work-for-1739](https://github.com/killbill/killbill/tree/work-for-1739) branch):** 

1. Code changes are made to update the CTD for `TRIAL`, `DISCOUNT` and `FIXEDTERM` phases. Some side effects of this:

- A `FIXED` invoice item generated corresponding to a subscription in a `TRIAL` phase will now have a non-null end date
- Cancellations requested without a date/cancellation policy will now be done `END_OF_TERM` if the subscription is  in the `TRIAL` phase (as against IMMEDIATELY as per the earlier behavior)
2. The above changes caused a lot of Java tests to fail. These are all fixed. 
3. This also caused e2e tests to fail. These are fixed in the [killbill-integration-tests/tests-for-1739](https://github.com/killbill/killbill-integration-tests/tree/tests-for-1739) branch.



**Work Remaining:**

There is a corner case related to the change alignment rule that does not work yet. The following issues exist:
1. [These e2e tests](https://github.com/killbill/killbill-integration-tests/blob/bb75f21a27972607f0cd312f3968f56b12cb1a4c/killbill-integration-tests/core/test_catalog.rb#L180:L274) fail after the changes to update the CTD for `TRIAL/DISCOUNT/FIXEDTERM`. These need to be investigated and fixed 
2. When an addon plan is changed with `START_OF_BUNDLE` change alignment rule, we would want the ADDON CTD to be aligned with the base CTD. However, this does not happen.
