### ISSUE TITLE
Improve handling of plugins that don't start well

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#1911]
When starting a Kill Bill instance today, there is a best effort attempt to start all plugins, but if somehow some of them don't, the system still starts (although some plugins may not be started). This can be an issue as plugins may play a critical role (e.g tax plugin).

The following is available today:
* Healthcheck mechanism: An unhealthy plugin could fail its healthcheck and as a result the node could be taken out of rotation/shutdown/restarted,...
* Node info endpoint: One can fetch details about the cluster of Kill Bill nodes, and for each node determine which plugin got started and which one did not.

However, these mechanism may not be sufficient:
1. As soon as the node starts, even if it has not been put under rotation (to serve requests), processing of (ready) notifications will start, and without all plugins started, this could be an issue.
2. The healthcheck mechanism only works if plugin started (and is unhealthy) but does not really work if plugin has not even started.

**Comment by sbrossie** [comment]
Suggestions:
1. Introduce a new property to specify which plugins are mandatory for Kill Bill to start and report as being healthy
2. Introduce (another) new property to delay the processing of notifications (e.g. give enough time for the node to report as healthy and/or being killed)
3.

**Comment by sbrossie** [comment]
Suggestions:
1. Introduce a new property to specify which plugins are mandatory for Kill Bill to start and report as being healthy
2. Introduce (another) new property to delay the processing of notifications (e.g. give enough time for the node to report as healthy and/or being killed)

**Comment by sbrossie** [comment]
Kill Bill boot sequence relies on the running through the LifeCycle sequences. There are 2 sequences, each of them running through a number of 'levels':
* `STARTUP_PRE_EVENT_REGISTRATION` will run all levels up (and included) to `START_PLUGIN` (starting the plugins). This is called from [KillbillPlatformGuiceListener](https://github.com/killbill/killbill-platform/blob/master/server/src/main/java/org/killbill/billing/server/listeners/KillbillPlatformGuiceListener.java#L210C1-L210C1)
* `STARTUP_POST_EVENT_REGISTRATION` will run all remaining levels, i/e from `START_SERVICE` and up, so essentially starting the bus and notification queues.

The new property needs to specify a list of plugins that should be up and running.

**Comment by reshmabidikar** [comment]
Update on this: `NodeApi` is available in the [KillbillGuiceListener.startLifecycleStage2](https://github.com/killbill/killbill/blob/33aa3e9a65bf40de10edee7429341370488d4fb5/profiles/killbill/src/main/java/org/killbill/billing/server/listeners/KillbillGuiceListener.java#L126C29-L126C29) method. However, when the [NodeApi.getNodesInfo](https://github.com/killbill/killbill-api/blob/7ea823b25e8fd6299350ec62d700e265022be34e/src/main/java/org/killbill/billing/util/nodes/KillbillNodesApi.java#L37) method is invoked, it returns node information without plugin information. That is the [PluginInfo list](https://github.com/killbill/killbill-api/blob/7ea823b25e8fd6299350ec62d700e265022be34e/src/main/java/org/killbill/billing/util/nodes/NodeInfo.java#L42C21-L42C31) is empty. This is updated while running the `STARTUP_POST_EVENT_REGISTRATION` sequence. This is the code flow: [DefaultLifecycle.java.fireStartupSequencePostEventRegistration](https://github.com/killbill/killbill-platform/blob/57b0daa4360d809cd044fd040a49cd66c322470a/lifecycle/src/main/java/org/killbill/billing/lifecycle/DefaultLifecycle.java#L88C17-L88C57) --> [DefaultKillbillNodesService.start](https://github.com/killbill/killbill/blob/33aa3e9a65bf40de10edee7429341370488d4fb5/util/src/main/java/org/killbill/billing/util/nodes/DefaultKillbillNodesService.java#L106) --> [DefaultKillBillNodesServce.createBootNodeInfo](https://github.com/killbill/killbill/blob/33aa3e9a65bf40de10edee7429341370488d4fb5/util/src/main/java/org/killbill/billing/util/nodes/DefaultKillbillNodesService.java#L143) (This deletes the existing record in the `node_infos` table and inserts a new record that contains the plugin information). 

Due to the above, I think that we would need to use option 2 suggested above ( modifying the `fireStartupSequencePriorEventRegistration` method). I gave this a quick try and it works.  So here is what I think we would need to do:
1. Define a property (`org.killbill.billing.plugin.mandatory.plugins`)
2. Read it in the [BundleRegistry.startBundles](https://github.com/killbill/killbill-platform/blob/57b0daa4360d809cd044fd040a49cd66c322470a/osgi/src/main/java/org/killbill/billing/osgi/BundleRegistry.java#L101) method.
3. Check that every plugin from the mandatory list is started in this method. If not, throw an exception
4. Catch this exception in the [DefaultOSGIService#start](https://github.com/killbill/killbill-platform/blob/master/osgi/src/main/java/org/killbill/billing/osgi/DefaultOSGIService.java#L100) method and exit.

Does this make sense?

**Comment by sbrossie** [comment]
As part of https://github.com/killbill/killbill-platform/pull/148, we have introduced 2 new properties:
* `org.killbill.billing.plugin.mandatory.plugins` to specify the list of mandatory plugins
* `org.killbill.server.exit.on.lifecycle.error` to decide whether Kill Bill server should exist when mandatory plugins have not been correctly started.


This issue can be closed.
