### ISSUE TITLE
Issues with Fixed Term subscriptions showing Active after Expiry ( KB 0.24.4 )

### ISSUE THREAD

**Issue by KBbitsP** [killbill/killbill#1930]
Steps to reproduce : 

1) Use Killbill version 0.24.4 ( reproducible on 0.24.10 as well )
2) Use the catalog : https://github.com/killbill/killbill-docs/blob/4671dcd9da1cf021e85629ab67e3ffb6fb553bb1/catalogs/fixedterm-no-trial.xml
3) Create a subscription starting 1st September.
4) Query the endpoint https://killbill.github.io/slate/subscription.html#retrieve-a-subscription-by-id and observe the field billingEndDate.
5) Move the date to 25th October. 
6) Again query the endpoint https://killbill.github.io/slate/subscription.html#retrieve-a-subscription-by-id and observe the fields cancelledDate, billingEndDate and State. 
7) Check the subscription tab in Kaui. 

Observed Issues : 

1) For a fixed term subscription, fields cancelledDate and billingEndDate remain null at the time of creation of the subscription, during the period the subscription is active and after the fixed time period is over. 
2) The State of the subscription stays as 'Active' even after the subscription time period is finished.
3) Kaui continues to show the subscription as active in the subscriptions tab, however, if you try to cancel the subscription, a message is displayed showing that subscription is already expired. 

Expected : 

1) billingEndDate should take into account the fixed term period and cancelledDate should show correct date after the fixed subscription period is over.
2) The 'State' should correctly reflect that the subscription is Expired. 
3) Kaui subscription tab should show the correct status once the subscription is Expired.

**Comment by reshmabidikar** [comment]
I think the issue is in the [getSubscriptionForEntitlementId](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/entitlement/api/SubscriptionApi.java#L58) method. The tests the subscription module ([TestUserApiExpire](https://github.com/killbill/killbill/blob/master/subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiExpire.java)) check for the expired state (for ex. [this line](https://github.com/killbill/killbill/blob/33aa3e9a65bf40de10edee7429341370488d4fb5/subscription/src/test/java/org/killbill/billing/subscription/api/user/TestUserApiExpire.java#L387)) and work fine. However, in the beatrix test ([TestCatalogFixedTerm](https://github.com/killbill/killbill/blob/33aa3e9a65bf40de10edee7429341370488d4fb5/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogFixedTerm.java)) we missed adding a check for expired state (after [this line](https://github.com/killbill/killbill/blob/33aa3e9a65bf40de10edee7429341370488d4fb5/beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestCatalogFixedTerm.java#L89)). I added this locally and the test fails at this point.

**Comment by shaun-forgie** [comment]
Is this scheduled for a fix in a given release yet?

**Comment by shaun-forgie** [comment]
So do expired subscriptions return a cancelled date or will a new field be added called expired date?

**Comment by shaun-forgie** [comment]
this seem related to https://github.com/killbill/killbill/issues/1921
