### ISSUE TITLE
Invoice plugins not called on refund

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#1990]
70ebae3608a362028d486cea5d57c3cf03aaeb91 introduced a regression. Invoice plugins aren't called anymore for refunds (we don't adjust taxes on refunds anymore).

**Comment by reshmabidikar** [comment]
For [recordRefund](https://github.com/killbill/killbill/blob/b7dc94ada8f18513b49f1e5f58c930d49969ae22/invoice/src/main/java/org/killbill/billing/invoice/api/svcs/DefaultInvoiceInternalApi.java#L130), I think the [getAdditionalInvoiceItems](https://github.com/killbill/killbill-avatax-plugin/blob/08a56cc65fbe01736b1b7931731b88f32a9e59ed/src/main/java/org/killbill/billing/plugin/avatax/api/AvaTaxInvoicePluginApi.java#L81C34-L81C59) method needs to be invoked so that the plugin can return additional invoice items corresponding to refund. So, we would simply need to undo the change to `recordRefund` (that is invoke [InvoiceApiHelper#dispatchToInvoicePluginsAndInsertItems](https://github.com/killbill/killbill/blob/b7dc94ada8f18513b49f1e5f58c930d49969ae22/invoice/src/main/java/org/killbill/billing/invoice/api/InvoiceApiHelper.java#L75C30-L75C68) from the `recordRefund` method). If this makes sense, I will go ahead with the change.

**Comment by sbrossie** [comment]
Fixed in https://github.com/killbill/killbill/pull/1996
