### ISSUE TITLE
Create shopping cart API

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#219]
We want to be able to create subscriptions (e.g. a base plan with a few add-ons) in one go (transactional), and potentially create external charges too, but still generate a single invoice.

See https://github.com/killbill/killbill/issues/73.

**Comment by pierre** [comment]
See also https://github.com/killbill/killbill/issues/199.

**Comment by javier-gomez-hs** [comment]
@pierre 
Would you be able to provide more details to this ticket?
The idea of adding a base subscription with a few add-ons in one go already exists, but now we need this to happen in one single transaction? And generating one single invoice?
Am I right?

Thanks!

**Comment by pierre** [comment]
> The idea of adding a base subscription with a few add-ons in one go already exists

Yes: this ticket is to be able to also create one-off charges (i.e. external charges), all in the same invoice.

The difficulty is that we don't have a way to create a single transaction across multiple Kill Bill modules (entitlement/subscription and invoice), without playing with tags (error prone).

Are you starting on this? If so, I'll have to chat with @sbrossie to see what our options are regarding implementation.

**Comment by pierre** [comment]
@javier-gomez-hs: We have decided not to add the ability to create external charges in that API. Instead, we just want to be able to create multiple entitlements (across bundles) atomically.

Work is similar to #199 and the new API would look like:

```
List<Entitlement> createBaseEntitlementsWithAddOns(UUID accountId, Iterable<BaseEntitlementSpecifierWithAddOns> specifiers, Iterable<PluginProperty> properties, CallContext context) throws EntitlementApiException;

public interface BaseEntitlementSpecifierWithAddOns {
  String externalKey;
  Iterable<EntitlementSpecifier> entitlementSpecifier;
  LocalDate entitlementEffectiveDate;
  LocalDate billingEffectiveDate;
  boolean isMigrated;
}
```

The implementation will probably need to create bundles serially (i.e. not atomically) which is fine, since there is no side effect. However, all subscription events across all bundles need to be created atomically (to generate a single invoice).

A new corresponding API in JAX-RS needs to be added as well (and corresponding client changes).

Does that make sense?

**Comment by sbrossie** [comment]
@javier-gomez-hs It seems like you are done with most your tasks. Is this one your next piece? Does the description we provided make sense?

**Comment by javier-gomez-github** [comment]
@sbrossie @pierre 
Sorry I didn't see these comments. Remember that I had to change my account to this one.
The new description does make sense, so I'll start working on this one!

Thanks!

**Comment by javier-gomez-github** [comment]
@pierre @sbrossie 
I've started with the changes on this issue and found out that [here](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java#L244) the `executeWithPlugin` method receives the result of [this](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java#L209) method and the `pluginContext` that is being defined [here](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/entitlement/src/main/java/org/killbill/billing/entitlement/api/DefaultEntitlementApi.java#L197-L207)
In my new implementation, should I create a new context in `killbill-plugin-api` to build the new `PluginContext`?
I'm a little bit confused with this one!

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-github The entitlement plugin api will need to be extended to support the shopping card api. %he work should be very similar to what happened when Matias did the work for #199; you can see his PR [here](https://github.com/killbill/killbill-plugin-api/pull/4/files).

In particular you will need a new `OperationType` (e.g`CREATE_SHOPPING_CARD_SUBSCRIPTIONS`) [here](https://github.com/killbill/killbill-plugin-api/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/plugin/api/OperationType.java#L26)

Probably the [EntitlementContext](https://github.com/killbill/killbill-plugin-api/blob/master/entitlement/src/main/java/org/killbill/billing/entitlement/plugin/api/EntitlementContext.java#L27) will need to be modified to accept a `Iterable<BaseEntitlementSpecifierWithAddOns> specifiers`.

The goal is to make sure that all the details of the call is accessible from the plugin (when such plugin exists). You could check with Matias, this is very similar to what he did, but one level up where subscriptions are not restricted to one bundle but can span multiple bundles.

In the end, we could possibly deprecate the `createBaseEntitlementWithAddOns` since the one you are implementing is a superset of the other.

Let us know if this is still confusing.

**Comment by javier-gomez-github** [comment]
@pierre @sbrossie 
I've created the first PRs so you can start taking a look at the changes:

- killbill-api: https://github.com/killbill/killbill-api/pull/25
- killbill-plugin-api: https://github.com/killbill/killbill-plugin-api/pull/5
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/17
- killbill: https://github.com/killbill/killbill/pull/632

Please, if you have the time, take a look at the code and let me know if I should change anything.
In the meantime, I'll start writing new Integration tests to verify this new API.

Thanks!

**Comment by javier-gomez-github** [comment]
@pierre @sbrossie 
I forgot to create the `killbill-client-java` PR.
This is the full list of PRs for this issue:

- killbill-api: https://github.com/killbill/killbill-api/pull/25
- killbill-plugin-api: https://github.com/killbill/killbill-plugin-api/pull/5
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/17
- killbill: https://github.com/killbill/killbill/pull/632
- killbill-client-java: https://github.com/killbill/killbill-client-java/pull/49

Thanks!
