### ISSUE TITLE
Ability to disable profiling code in KillBill

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#231]
Currently all API, DAO calls are profiled (and returned if specific profiling header is provided). Since most of time profiling header is not provided, it would be nice to have a way to remove this extra layer:
For instance there is an extra proxy invocation for API:
https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/glue/KillbillApiAopModule.java

**Comment by pierre** [comment]
Wondering if it's actually worth it to make any code change here:

* The [Profiling](https://github.com/killbill/killbill-commons/blob/aef764bf9b818d2cddd4f33a25fbaae8bb5444b4/concurrent/src/main/java/org/killbill/commons/profiling/Profiling.java#L31-L34) class already returns fast. This takes care of [DefaultNonEntityDao](https://github.com/killbill/killbill/blob/84ec1b5f1cc196d8c8e47f1d800dc444c33dabc9/util/src/main/java/org/killbill/billing/util/dao/DefaultNonEntityDao.java#L189-L194) and the various invocations in [EntitySqlDaoWrapperInvocationHandler](https://github.com/killbill/killbill/blob/84ec1b5f1cc196d8c8e47f1d800dc444c33dabc9/util/src/main/java/org/killbill/billing/util/entity/dao/EntitySqlDaoWrapperInvocationHandler.java)
* The [JAX-RS filter](https://github.com/killbill/killbill/blob/84ec1b5f1cc196d8c8e47f1d800dc444c33dabc9/profiles/killbill/src/main/java/org/killbill/billing/server/filters/ProfilingContainerResponseFilter.java#L57) doesn't do anything either if no header is passed
* It's true though that [KillbillApiAopModule](https://github.com/killbill/killbill/blob/84ec1b5f1cc196d8c8e47f1d800dc444c33dabc9/util/src/main/java/org/killbill/billing/util/glue/KillbillApiAopModule.java#L43) wraps all API calls, but the call is a no-op if no header is provider

We could add a system property for that last piece. However, for convenience, and due to the low overhead, I would argue to have it enabled by default, even in production.

So, worth it?

**Comment by sbrossie** [comment]
I don't think this worth too much effort...

> We could add a system property for that last piece. However, for convenience, and due to the low overhead, I would argue to have it enabled by default, even in production.

Adding system property to change the way we dispatch api calls is tricky (that provides a very different runtime path with potentially their own bugs,...)
