### ISSUE TITLE
Retrieving a subscription does not return the 'events' attached to the subscription

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#244]
After creating a subscriptions (and going through overdue phases, we can see all the events are set to null:

```
> curl -v \
-u admin:password \
-H "X-Killbill-ApiKey: test-api-key1418166651-614031" \
-H "X-Killbill-ApiSecret: test-api-secret1418166651-614031" \
-H "Content-Type: application/json" \
-H "X-Killbill-CreatedBy: demo" \
"http://127.0.0.1:8080/1.0/kb/subscriptions/9d53a5b4-20bf-43dd-b45f-53845aab61e2"

{"accountId":"834f80c6-d7d2-4935-9618-3dc0ca97a966","bundleId":"8f85302a-0f3a-4fd6-bbca-211dbf5918f5","subscriptionId":"9d53a5b4-20bf-43dd-b45f-53845aab61e2","externalKey":"834f80c6-d7d2-4935-9618-3dc0ca97a966-1418166653","startDate":"2013-08-01","productName":"Sports","productCategory":"BASE","billingPeriod":"MONTHLY","priceList":"DEFAULT","cancelledDate":null,"chargedThroughDate":"2013-10-31","billingStartDate":"2013-08-01","billingEndDate":null,"events":null,"newEvents":null,"deletedEvents":null,"auditLogs":null}```

**Comment by pierre** [comment]
Today, we only expose subscription events at the bundle level, across all entitlements (see `SubscriptionBundleTimeline`). This is done by computing all `Subscription` objects (including their base and blocking events), and then merging all of these events in a continuous, ordered, list of events across the bundle (done in `DefaultSubscriptionBundleTimeline`).

The work is simply to expose these events at the `Subscription` level ([proposed API change](https://github.com/killbill/killbill-api/commit/e06dbf62ca19158734ed05a7cb71376ffa5c2b34)). The ordering code from `DefaultSubscriptionBundleTimeline` can be extracted, and called both from  `Subscription` and  `SubscriptionBundleTimeline`.

Because we already compute these events today when building the `Subscription` object (even though we don't return them), the only performance hit will be the extra merging/sorting in memory to build the ordered list to present to the user (no extra DAO call).

**Comment by pierre** [comment]
A note on JAX-RS: `SubscriptionJson` already exposes `List<EventSubscriptionJson> events` (populated by filtering the events from `SubscriptionBundleTimeline`), so this new Java API change will mimic what we already do in JAX-RS.

Unfortunately, `BundleJson` doesn't expose `SubscriptionBundleTimeline`, which is a bit unfortunate because we already have the complicated code to build it. As part of this, I'm suggesting we extend `BundleJson` to expose `BundleTimelineJson`.

**Comment by sbrossie** [comment]
Sure, the only penalty is that now when retrieving the bundle we also have to recompute all the things for SubscriptionBundleTimeline, but probably worth it.

**Comment by pierre** [comment]
It's actually already the case today: `SubscriptionBundle` includes `SubscriptionBundleTimeline`. It was just never exported to JAX-RS.

**Comment by sbrossie** [comment]
Ah well, in that case, let's finish the work!
