### ISSUE TITLE
Ability to exclude control tag type in OverdueCondition

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#256]
We already have the ability to define in the `overdue.xml` a control tag type to match per condition (e.g. overdue condition only for `MANUAL_PAY` accounts). It would be nice to also have the opposite (i.e. overdue condition to match all but `MANUAL_PAY` accounts).

See https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/overdue/api/OverdueCondition.java#L37.

**Comment by sbrossie** [comment]
Actually the [current tag logic is not even implemented](https://github.com/killbill/killbill/blob/killbill-0.16.2/overdue/src/main/java/org/killbill/billing/overdue/calculator/BillingStateCalculator.java#L78) so probably we should start there?

Questions:
* Should we only look for the tags on the account object ( i am guessing so, since all our system tag are `ACCOUNT` level except for `WRITTEN_OFF` which should already be handled correctly in the context of the overdue system?
* Also the current overdue xml allows to specify only one tag `ControlTagType controlTag`; it seems like we may want a set?
* Finally do we want to replace the current (not yet implemented) logic of looking for inclusion and instead looking for exclusion-- it seems more interesting i agree (e.g evaluate condition negatively if account is in `MANUAL_PAY`). Or do we really want both?

**Comment by pierre** [comment]
Some thoughts:

1. Only looking at account tags sounds good
2. Alternatively, we could have the user duplicate rules for different tags (to simplify the problem "all-or-at-least-one matches")
3. Intuitively, we need both: for example, one set of rules for all but `PARTNER` accounts and one set of rules (maybe more relaxed) for `PARTNER` accounts?

**Comment by sbrossie** [comment]
@matias-aguero-hs 

Based on @pierre 's thoughts above (and a discussion we just had):
1. Only looking at account tags [and implement it](https://github.com/killbill/killbill/blob/killbill-0.17.2/overdue/src/main/java/org/killbill/billing/overdue/calculator/BillingStateCalculator.java#L78)
2. I would keep one one tag (don't implement the sequence) to keep things simpler.
3. However work is to add the negative condition, `isTagNotIn`, similar to what we do [here](https://github.com/killbill/killbill/blob/killbill-0.17.2/overdue/src/main/java/org/killbill/billing/overdue/config/DefaultOverdueCondition.java#L76)

**Comment by matias-aguero-hs** [comment]
Guys, these are the PRs for this issue:
- killbill-api: https://github.com/killbill/killbill-api/pull/19
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/10
- killbill: https://github.com/killbill/killbill/pull/597
