### ISSUE TITLE
Accessing the list of registered plugins from plugins

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#331]
Routing plugins need to make decisions on where to route the payments based on internal routing logic, but also based on the list of available registered plugins. Getting that list is not easy today. Do we need a new API?

**Comment by sbrossie** [comment]
Or maybe we should just extend the [PaymentRoutingContext](https://github.com/killbill/killbill-plugin-api/blob/master/routing/src/main/java/org/killbill/billing/routing/plugin/api/PaymentRoutingContext.java) to pass the list of paymentControlPluginNames

**Comment by sbrossie** [comment]
Also by looking at this API, just realized that although PaymentRoutingContext contains `Iterable<PluginProperty> getPluginProperties();` we still pass `Iterable<PluginProperty> getPluginProperties();` in each API, so i could fix it at the same time

**Comment by pierre** [comment]
> Or maybe we should just extend the `PaymentRoutingContext` to pass the list of paymentControlPluginNames

You meant paymentPluginNames, not paymentControlPluginNames, right? If so, :+1:, much easier.

> Also by looking at this API, just realized that although PaymentRoutingContext contains `Iterable<PluginProperty> getPluginProperties();` we still pass `Iterable<PluginProperty> getPluginProperties();` in each API, so i could fix it at the same time

Actually, we did this on purpose IIRC. Conceptually, `PaymentRoutingContext#getPluginProperties` are plugin properties that are passed to the payment plugin, and the ones in the API are the plugin properties for the control plugin itself. I think they are the same in practice today, but we could have finer control in the future.

**Comment by sbrossie** [comment]
>> Or maybe we should just extend the `PaymentRoutingContext` to pass the list of paymentControlPluginNames

> You meant paymentPluginNames, not paymentControlPluginNames, right? If so, :+1:, much easier.

Ah, ah, actually the title of the issue does not specify whether it was to access 'payment plugin' or 'payment control plugins', so i had assumed the latest. But this is actually *really* interesting to bring that back in the picture, because now i join you back on in the original comment of having a new API:

The reason is that we have many different plugins type, and so shoving info about which plugins of a given type are registered in the `PaymentRoutingContext` might solve our immediate use case, but we could have many other use case for other KB parts or other plugins to access that kind of info.

Maybe a new PluginInfoApi which returns for each plugin type, which plugin are registered and when order matter what is the order might make sense.

Other use cases:
* From a UI point of view, querying all existing registered plugins, and then from that list UI could query each plugin individually to retrieve specific info
* From a validation point of view (had the discussion with Martin recently about doing more plugin property validation), this could also be useful

**Comment by pierre** [comment]
> From a UI point of view, querying all existing registered plugins, and then from that list UI could query each plugin individually to retrieve specific info

Indeed - it would be nice for payment plugins to expose capabilities. For example, the checkout app could ask what payment methods are available in a given country, acquirers configuration, if a mobile experience for HPP exists, etc.

**Comment by pierre** [comment]
> Indeed - it would be nice for payment plugins to expose capabilities. For example, the checkout app could ask what payment methods are available in a given country, acquirers configuration, if a mobile experience for HPP exists, etc.

See also https://github.com/killbill/killbill/issues/194.

**Comment by pierre** [comment]
Done with the [KillbillNodesApi](https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/util/nodes/KillbillNodesApi.java) API.
