### ISSUE TITLE
Revisit IncompletePaymentTransactionTask#MAX_ITEMS_PER_LOOP

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#343]
By default, we read at most 100 transactions to repair per hour. This can be an issue if the first 100 ones are stuck in an `UNKNOWN` state, while others are ready to be transitioned (they will potentially never be taken into account).

It seems that even if we have thousands of transactions, all of them should be run through the task periodically. We could maybe re-use `DefaultPaginationSqlDaoHelper` to go through all efficiently?

**Comment by sbrossie** [comment]
There are few issues that need to be addressed:
1. The current query that limits to 100 is a problem in itself, because if those entries don't transition, we will keep processing the first 100 entries and not the rest,
2. Ideally, we should be able to distinguish between PENDING payments (that will transition fast, like in HPP scenario), or PENDING that will transition slow (ACH like)
3. We would like to not keep re-processing the same entries where previous iterations have failed, and have some kind of smarter logic (exponential reties...)
