### ISSUE TITLE
Beatrix TestConsumableInArrear tests failing

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#382]
They are failing on Travis as well as locally:

```
Tests run: 222, Failures: 2, Errors: 0, Skipped: 216, Time elapsed: 31.343 sec <<< FAILURE!
testSimple(org.killbill.billing.beatrix.integration.usage.TestConsumableInArrear)  Time elapsed: 2.234 sec  <<< FAILURE!
java.lang.AssertionError: TestApiListener [ApiListenerStatus]: Received unexpected event CREATE; remaining expected events [PHASE INVOICE PAYMENT]
	at org.testng.Assert.fail(Assert.java:94)
	at org.killbill.billing.api.TestApiListener.assertListenerStatus(TestApiListener.java:88)
	at org.killbill.billing.beatrix.integration.TestIntegrationBase.assertListenerStatus(TestIntegrationBase.java:259)
	at org.killbill.billing.beatrix.integration.usage.TestConsumableInArrear.testSimple(TestConsumableInArrear.java:77)

afterMethod(org.killbill.billing.beatrix.integration.usage.TestConsumableInArrear)  Time elapsed: 2.234 sec  <<< FAILURE!
java.lang.AssertionError: TestApiListener [ApiListenerStatus]: Received unexpected event CREATE; remaining expected events [PHASE INVOICE PAYMENT]
	at org.testng.Assert.fail(Assert.java:94)
	at org.killbill.billing.api.TestApiListener.assertListenerStatus(TestApiListener.java:88)
	at org.killbill.billing.beatrix.integration.TestIntegrationBase.assertListenerStatus(TestIntegrationBase.java:259)
	at org.killbill.billing.beatrix.integration.TestIntegrationBase.afterMethod(TestIntegrationBase.java:298)
```

**Comment by sbrossie** [comment]
This is often seen in the Travis build (e.g https://travis-ci.org/killbill/killbill/jobs/77005185)

**Comment by sbrossie** [comment]
Most of our travis failures these days are related to the test `TestConsumableInArrear` which is failing when executed with the profile `postgresql`. After some investigation, it looks like the bus events are dispatched multiple times causing the test to fail because it sees unexpected events:

```
[main] ERROR org.killbill.billing.api.TestApiListener - TestApiListener [ApiListenerStatus]: Received unexpected event CREATE; remaining expected events [PHASE INVOICE PAYMENT]
java.lang.AssertionError: TestApiListener [ApiListenerStatus]: Received unexpected event CREATE; remaining expected events [PHASE INVOICE PAYMENT]
```

After investigation(looking into bus_events_history) i realized, that there are indeed additional events than expected.

I believe the reason is that our [queue code](https://github.com/killbill/killbill-commons/blob/master/queue/src/main/java/org/killbill/queue/DBBackedQueue.java#L598) , in its logic where it claims entries relies on the result of the update call to be set to 1. 

It seems like postgres by default will not return the number of rows updated breaking our current claim logic, and causing the test to fail. There is a [possible solution](http://stackoverflow.com/questions/4038616/get-count-of-records-affected-by-insert-or-update-in-postgresql) here but that seems a bit complicated.

**Comment by sbrossie** [comment]
@pierre Probably we should disable `postgresql` on travis until we get that fixed?

**Comment by pierre** [comment]
This is still happening on MySQL: https://travis-ci.org/killbill/killbill/builds/102363371.
