### ISSUE TITLE
NPE when creating external charges

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#388]
If no currency is specified, InvoiceItemJson#currency is null and [this check](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L472) will throw an NPE.

**Comment by sbrossie** [comment]
@pierre I am bit confused because it looks like [we expect the currency to be set for each item](https://github.com/killbill/killbill-client-java/blob/master/src/main/java/org/killbill/billing/client/KillBillClient.java#L610). Should we remove that in our client and fix the server to default to account currency when this has not been specified?
