### ISSUE TITLE
Verify that getPaymentInfo/getPaymentMethods works for built-in __EXTERNAL_PAYMENT__ plugin

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#41]
~~When asking for plugin specific information for external payments, the call will almost always fail since not all of the payments are kept in memory.~~

**Comment by sbrossie** [comment]
The build-in `ExternalPaymentProviderPlugin` which is used to implement the `__EXTERNAL_PAYMENT__` payment method does not keep anything in memory. When we make payment operation such as `getPaymentInfo` and `getPaymentMethods ` and specify the flag `withPluginInfo` = true, nothing will be returned from the plugin (`ExternalPaymentProviderPlugin`).

The work is to add some test cases to verify that those operations work and return the right things.

**Comment by sbrossie** [comment]
We could write a test `TestExternalPaymentPlugin` similar to [TestPaymentApi](https://github.com/killbill/killbill/blob/master/payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApi.java), where instead of registering the `MockPaymentProviderPlugin` we would register the `ExternalPaymentProviderPlugin ` plugin.

**Comment by maguero** [comment]
There is an existing [TestExternalPaymentProviderPlugin] (https://github.com/killbill/killbill/blob/master/payment/src/test/java/org/killbill/billing/payment/provider/TestExternalPaymentProviderPlugin.java#L66-L68), should I work on this class?
In the other hand, what cases do you recommend me to verify?

In addition, some methods like [getPaymentInfo] (https://github.com/killbill/killbill/blob/master/payment/src/main/java/org/killbill/billing/payment/provider/ExternalPaymentProviderPlugin.java#L88) always return an empty list.

**Comment by sbrossie** [comment]
@maguero The `__EXTERNAL_PAYMENT__` plugin does not store state persistently (and we don't want to change that since there is nothing interesting to store as it does not communicate with any payment gateways).

> In addition, some methods like getPaymentInfo always return an empty list

Yes this is expected. What we want to verify is that for those payments, payment calls like  `getPaymentInfo` and `getPaymentMethods` when invoked with the flag `withPluginInfo = true` will end up returning nothing and yet the call should succeed and provide the default payment info (with no plugin info).

The test you could modify is [TestPaymentApi](https://github.com/killbill/killbill/blob/master/payment/src/test/java/org/killbill/billing/payment/api/TestPaymentApi.java) (and not `TestExternalPaymentProviderPlugin` which is too low level to be interesting)

**Comment by maguero** [comment]
@sbrossie: thank you for  the clarifications. 
I wonder if you can take a look to my test before create the PR to check if we are on the same page.
https://github.com/maguero/killbill/commit/e4164b4ff9214db9862fd69202d6c352e5eeede7

**Comment by sbrossie** [comment]
@maguero Just commented on the test. Overall looks good.

**Comment by maguero** [comment]
Thank you!
PR created: https://github.com/killbill/killbill/pull/412
