### ISSUE TITLE
Hierarchical account: account module implementation

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#456]
Add the following new fields in the `accounts` table:

* `parent_account_id`
* `is_payment_delegated_to_parent`

Modify create/update/get api to include those fields. (the modification for update is to *not* allow the update.
Modify DAO/DDL
Modify `ImmutableAccountData` to include those fields

Clients libraries need to be updated as well (`java` + `ruby`)

Tests:

* Unit tests in account (especially update path)
* JAXRS tests

**Comment by sbrossie** [comment]
Until we resolve the question around un-parenting or re-parenting, let's not do anything with `ImmutableAccountData` (i.e no additional caching).

**Comment by matias-aguero-hs** [comment]
> the modification for update is to not allow the update

Do you mean that `parentAccountId` and `isPaymentDelegatedToParent`cannot be changed?

**Comment by pierre** [comment]
> Do you mean that `parentAccountId` and `isPaymentDelegatedToParent`cannot be changed?

This was the thought originally (hence the additional caching work required in `ImmutableAccountData`). But since we're now investigating re-parenting and de-parenting, these might be updatable in the future.
For now, for simplicity, let's just assume these won't be updated (but don't enforce it in the code just yet).

**Comment by matias-aguero-hs** [comment]
thanks.

**Comment by matias-aguero-hs** [comment]
As @sbrossie suggested, can you please create new branches so I can create PRs?

* killbill
* killbill-api
* killbill-client-java
* killbill-oss-parent (should we also merge version changes here?)

(Unfortunately, we can't address ruby client now)

**Comment by pierre** [comment]
Done!

* https://github.com/killbill/killbill/tree/hierarchical-accounts
* https://github.com/killbill/killbill-api/tree/hierarchical-accounts
* https://github.com/killbill/killbill-client-java/tree/hierarchical-accounts
* https://github.com/killbill/killbill-oss-parent/tree/hierarchical-accounts

Regarding versions, I've added `.ha` to all versions to avoid any confusion (e.g. `0.17.0.ha-SNAPSHOT` for  killbill, `0.80.ha-SNAPSHOT` for killbill-oss-parent, etc.). Please do the same if you need to update other repos.

About the ruby client, it's probably fine for now, but just so you know, we will need to address it before being able to release 0.17.0 (otherwise the integration tests, Kaui, etc. might break).

**Comment by matias-aguero-hs** [comment]
First group of PRs:

* killbill-api: https://github.com/killbill/killbill-api/pull/9
* killbill-client-java: https://github.com/killbill/killbill-client-java/pull/24
* killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/5
* killbill: https://github.com/killbill/killbill/pull/468

Notes: "update" method need to be discussed after decide "re-parenting and de-parenting" feature.

**Comment by pierre** [comment]
Thanks. Could you make sure though that the PRs only contain changes for the account module (I see invoice changes for example)?

Also, I am not sure we want to introduce a `getInvoicesByParentAccount` API, or at least not in this form (modules should always communicate by APIs or by bus event, we should never join cross-module tables directly).

**Comment by matias-aguero-hs** [comment]
Done. I removed Invoices changes from this task.

**Comment by matias-aguero-hs** [comment]
I had to create a new PR: https://github.com/killbill/killbill-api/pull/10

**Comment by matias-aguero-hs** [comment]
Do you think we are ok on this task? I'm also ready to start merging #457.

**Comment by pierre** [comment]
> Do you think we are ok on this task?

Yup, I just merged it (FYI, I don't get any notification when a PR is updated).

Keeping this task open to track the following items:

* Un-parenting and re-parenting feature
* Additional caching in `ImmutableAccountData`
* Ruby client changes

**Comment by matias-aguero-hs** [comment]
> (FYI, I don't get any notification when a PR is updated)

Ohh, I see. 

> Keeping this task open

Sure, we'll be back on them later.

Thanks.
