### ISSUE TITLE
Overdue changes to support Hierarchical Account

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#458]
For all the existing overdue handlers in `OverdueListener` the code needs to now detect when this is parent account and propagate the changes to the children (in addition to itself).

`OverduePoster` needs to be called to create a new notification for each child so processing happens asynchronously

Tests:

* Create unit in overdue with one parent and a few children

**Comment by sbrossie** [comment]
There are two possible models:

* A first model where the children overdue states are managed on their own (e.g on child could be in CLEAR state whole parent is already in overdue STATE_1 because its first unpaid summary invoice was not paid, and there was no item for that child)
* A second model where children overdue state map exactly to the one for the parent

So, it seems we need some configuration to decide which model to use (probably a new column in the account table for the parent account).

In the first model, this is what already exists today, and this should suffice for the children. For the parent this is less clear (should we also compute the state based on the summary invoices).

In the second model, the parent will set the children state (blockingState), and also add some notification for children to take actions (e.g cancel subscriptions in final state).

**Comment by matias-aguero-hs** [comment]
I have been working on this ticket, and I just pushed the code related to second model described above: `A second model where children overdue state map exactly to the one for the parent`

> OverduePoster needs to be called to create a new notification for each child so processing happens asynchronously

First, I implemented the logic in [OverdueListener](https://github.com/killbill/killbill/blob/hierarchical-accounts/overdue/src/main/java/org/killbill/billing/overdue/listener/OverdueListener.java#L142-L143) to send one notification per each parent and children accounts. It worked until the payments are made successfully. Once payment are OK, and accounts need to be set as clear again the child account still in OD3 state and it was because [billingState](https://github.com/killbill/killbill/blob/hierarchical-accounts/overdue/src/main/java/org/killbill/billing/overdue/wrapper/OverdueWrapper.java#L100) and [calculateOverdueState](https://github.com/killbill/killbill/blob/hierarchical-accounts/overdue/src/main/java/org/killbill/billing/overdue/config/DefaultOverdueCondition.java#L64-L77) detects unpaidInvoices in childAccount.

Then, I changed the approach and I implemented it directly on [OverdueWrapper.refreshWithLock](https://github.com/matias-aguero-hs/killbill/blob/3b2a09d7b219e0d15435191adb71e5aae2993ad3/overdue/src/main/java/org/killbill/billing/overdue/wrapper/OverdueWrapper.java#L118-L136) method. I'm not sure if thats ok for you, because you mentioned `... processing happens asynchronously`.

Please let me know what do you think. Commit: https://github.com/matias-aguero-hs/killbill/commit/3b2a09d7b219e0d15435191adb71e5aae2993ad3

In the other hand:

> - A first model where the children overdue states are managed on their own (e.g on child could be in CLEAR state whole parent is already in overdue STATE_1 because its first unpaid summary invoice was not paid, and there was no item for that child)

> So, it seems we need some configuration to decide which model to use (probably a new column in the account table for the parent account).

Do you still contemplate to add a new column on parent account? We are not marking an account as parent currently, so adding a new column will involve to ensure set this column when the parent account is created.

Thanks.

**Comment by sbrossie** [comment]
You code looks good, i commented on the diff. Some additional overall comments:
1. I would suggest to *only* implement one model for now. Maybe something else to check with Joe (if he is happy with model 2 maybe this is all we implement for now).  Therefore i would refrain before adding the new account column
2. I would focus on adding more tests (think of interesting use cases). Also, if there is a way to add lower level tests (maybe in overdue module itself by mocking things) that could be powerful.

**Comment by matias-aguero-hs** [comment]
> 1. I would suggest to only implement one model for now. Maybe something else to check with Joe (if he is happy with model 2 maybe this is all we implement for now)...

I'll check with him.

> 2. I would focus on adding more tests (think of interesting use cases). Also, if there is a way to add lower level tests (maybe in overdue module itself by mocking things) that could be powerful.

👍 

Thanks.

**Comment by matias-aguero-hs** [comment]
@sbrossie I created a PR https://github.com/killbill/killbill/pull/577.

After some tests and debugs I had bad results implementing child notifications in `OverdueWrapper`. It seems that notifications are override or something like that and some child accounts were not refreshed properly. I moved it back to `OverdueListener` and it's working now.

**Comment by sbrossie** [comment]
@maguero Ok, i might need a bit more info: By making this change you are basically switching model. Initially you implemented model `2`, where each child inherits the exact same overdue status as the parent. Now, the logic is to have each child recompute its overdue status (model `1`).

So, there is first a product question, which is to decide which model we need to implement. Please check with Joe, and based on what he says we can decide which route to go (or we implement both :-) )

Also, i would be curious to understand what does not work with your previous implementation; if you could at least narrow it down, that would be really interesting (Maybe time box it: if this is too difficult and we end up implementing model 1, then it's fine to drop it too)

**Comment by matias-aguero-hs** [comment]
> Initially you implemented model 2, where each child inherits the exact same overdue status as the parent. Now, the logic is to have each child recompute its overdue status (model 1).

Actually I'm implementing model 2, the only condition is that child account delegates payment to parent. The code is [computing the parent overdue](https://github.com/matias-aguero-hs/killbill/blob/458-ha-overdue/overdue/src/main/java/org/killbill/billing/overdue/wrapper/OverdueWrapper.java#L137-L138) instead of child one. In [Overdue test](https://github.com/matias-aguero-hs/killbill/blob/458-ha-overdue/beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueChildParentRelationship.java#L104) there are 4 child account with different situations, and you can see that the first three have `isPaymentDelegatedToParent=true` and are map to parent status no matter what child billing state it has.

>So, there is first a product question, which is to decide which model we need to implement. Please check with Joe, and based on what he says we can decide which route to go (or we implement both :-) )

Joe told me that implementing model 2 is enough for him.

>Also, i would be curious to understand what does not work with your previous implementation...

It's weird... when I ran test normally it failed and only some child accounts maps with parent account status, but if I put a breakpoint in `overdueStateApplicator.apply(....)` line inside of `OverdueWrapper` and wait a second before press "continue" the test pass successfully and all child accounts map with parent account status.

**Comment by sbrossie** [comment]
@maguero I just merged your PR, but i am still confused on which model got implemented:

In the [code you are referring too](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/overdue/src/main/java/org/killbill/billing/overdue/wrapper/OverdueWrapper.java#L141) we see that:
* `overdueable` is the child account
*, `parentAccountContext` as its name indicates is the context for the parent.

The method [calculateBillingState](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/overdue/src/main/java/org/killbill/billing/overdue/calculator/BillingStateCalculator.java#L66) is relying on the `overduable` (child) to compute unpaid invoices, so will the overdue status not be tied to the child then? Am i missing something?

**Comment by matias-aguero-hs** [comment]
You're right, the code is sending `childAccount` object and `parentAccountContext`. The unpaid invoices are [retrieving by context](https://github.com/matias-aguero-hs/killbill/blob/3b2a09d7b219e0d15435191adb71e5aae2993ad3/invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java#L170-L170) and childAccount object is used to build the [BillingState](https://github.com/matias-aguero-hs/killbill/blob/5bec17deadf78b5a08edac408b1dcc7bb765b50d/overdue/src/main/java/org/killbill/billing/overdue/calculator/BillingStateCalculator.java#L80-L80) object result. That's why the code is using both accounts.

**Comment by sbrossie** [comment]
@matias-aguero-hs I see... our [api is a bit confusing](https://github.com/killbill/killbill/blob/killbill-0.17.1/invoice/src/main/java/org/killbill/billing/invoice/dao/InvoiceDaoHelper.java#L170) (and broken in my opinion) and you just took advantage of that: We allow to pass both an `accountId` and a context (which contains an `accountRecordId`). The assumption is that both `accountId` and `accountRecordId` should point to same account, but there is nothing enforcing that, so what you described is correct.

At some point we will need to revisit that (at the very least add some comments) and a better solution would be to remove `accountId` and simply rely on the context. This is fine for now. Nothing to do. Let's move on.
