### ISSUE TITLE
Some entitlement APIs don't go through entitlement plugins

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#469]
See `DefaultEntitlement#cancelEntitlementWithDate` for example.

**Comment by sbrossie** [comment]
Note that there is a remaining call (DefaultEntitlement#uncancelEntitlement)that has not been wrapped around the entitlement plugin. However in order to fix it we need to add a new enum value `UNCANCEL` in the `OperationType` and that requires a api change. 

Moving the issue into milestone Release-0.17.0
