### ISSUE TITLE
Investigate Travis failures

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#485]

**Comment by sbrossie** [comment]
@pierre Any link i could use to investigate?

**Comment by pierre** [comment]
See for example https://s3.amazonaws.com/archive.travis-ci.org/jobs/106473349/log.txt.

**Comment by sbrossie** [comment]
By looking at Travis failures for KB, i see a lot of test failures (all over the board, and probably because environment in so different). For instance, just looking at last failed 3 logs:
```
TestPaymentApi.beforeMethod:95 » PaymentApi Plugin timeout for account 80428f7... (https://travis-ci.org/killbill/killbill/jobs/125895558)
TestUserApiCancel.testUncancel:227->SubscriptionTestSuiteWithEmbeddedDB.assertListenerStatus:147 expected [true] but found [false]
TestUserApiCancel>SubscriptionTestSuiteWithEmbeddedDB.afterMethod:131->SubscriptionTestSuiteWithEmbeddedDB.assertListenerStatus:147 TestApiListener [ApiListenerStatus]: Received unexpected event UNCANCEL; remaining expected events []
TestBundleTransfer.testBundleTransferWithBPMonthlyOnlyWIthCancellationImm:194->TestIntegrationBase.assertListenerStatus:272 expected [true] but found [false]
TestPaymentRefund.beforeMethod:70->setupRefundTest:129 expected [0] but found [1]
TestPushNotification.testPushNotification:112 Assertion during callback failed...
```

**Comment by sbrossie** [comment]
In order to help recreate the issues (which i can't reproduce on my local box), i spawned a small instance on EC2.

For reference:
* I used a  `t2.medium` (2 virtual cores) using AMI `ubuntu-trusty-14.04-amd64-server-20160114.5 (ami-9abea4fb)`
* I setup the zone, the following way:
```
apt-get update && \
apt-get install -y \
openjdk-7-jdk \
curl \
mysql-client \
mysql-server \
tomcat7 \
libtcnative-1 \
telnet \
git \
maven
```

I then enabled our tests to log the time for each log line killbill/killbill-oss-parent@6b33345c1f9a271a4f0c828002227cc07d07b913 and reran the tests:

What i observed is that some assertion failed because there is a serious timing issue in the log (probably due to sharing CPU with other machines). What we see in that log is that:
1. We move the clock at `23:12.254` and expect 2 events to be processed
2. The next trace occurs 25 sec later at `00:23:37.291` as expected because our `TestApiListener` is configured to timeout after 25 sec.
3. We eventually get the first event notification (and i confirmed by looking at the DB, that it was indeed processed) at `00:23:56.306`, which **44 sec** later! 

```
2016-04-29T00:23:12.254+0000 [main] INFO org.killbill.clock.ClockMock -             ************      ADJUSTING CLOCK FROM 2012-06-04T00:03:44.000Z to 2012-06-09T00:03:44.000Z     ********************
2016-04-29T00:23:37.291+0000 [main] ERROR org.killbill.billing.api.TestApiListener - TestApiListener did not complete in 25000 ms, remaining events are PHASE PHASE
2016-04-29T00:23:56.306+0000 [bus_events-th] INFO org.killbill.billing.api.TestApiListener - Got subscription event DefaultEffectiveSubscriptionEvent{bundleId=800f4c55-b36f-415d-a2c0-fe5719241509, totalOrdering=2, subscriptionId=46eb764b-1972-499b-92c3-12c88c0f816f, eventId=29a62d1d-427b-4b8a-b8af-3f13e4e99099, requestedTransitionTime=2012-06-06T00:03:43.000Z, effectiveTransitionTime=2012-06-06T00:03:43.000Z, previousState=ACTIVE, previousPriceList='DEFAULT', previousPlan='shotgun-monthly', previousPhase='shotgun-monthly-trial', nextState=ACTIVE, nextPriceList='DEFAULT', nextPlan='shotgun-monthly', nextPhase='shotgun-monthly-evergreen', remainingEventsForUserOperation=0, transitionType=PHASE, startDate=2012-05-07T00:03:43.000Z}
2
```

**Comment by sbrossie** [comment]
Error in [`TestBundle.testBundlesPagination:159->KillbillClient.createEntitlement:122 » KillBillClient`](https://travis-ci.org/killbill/killbill/jobs/127947867)

**Comment by pierre** [comment]
`TestOverdueIntegration.testOverdueStateIfNoPaymentMethod` is now failing locally too in branch `work-for-release-0.16.7`.

**Comment by pierre** [comment]
The issue with `TestOverdueIntegration.testOverdueStateIfNoPaymentMethod` has been fixed by https://github.com/killbill/killbill/commit/21d0b541d7b5687ca1bec5db2fd8defa880a437e.

Otherwise, the build has been pretty stable lately... :trophy:

![image](https://cloud.githubusercontent.com/assets/51940/16535378/a8bfc33e-3f9b-11e6-946b-8aa093cdf140.png)

**Comment by sbrossie** [comment]
🙌
