### ISSUE TITLE
In-memory external bus should trigger retries

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#503]
Currently, exceptions from the external bus are swallowed when it is configured in-memory. Instead, they should be re-thrown to the internal bus, to trigger a retry.

As part of this, we should make sure that there are no side-effects for the persistent bus (e.g. we don't want to retry twice, from both buses, in case of exceptions).

**Comment by sbrossie** [comment]
There seems be another issue when using in-memory bus. The [current code](https://github.com/killbill/killbill-commons/blob/master/queue/src/main/java/org/killbill/bus/InMemoryPersistentBus.java#L60) relies on the guava `EventBus` implementation instead of using the custom `EventBusThatThrowsException` implementation. That will need to be fixed as well to make sure exceptions are not swallowed by guava.
