### ISSUE TITLE
Configure default state machine to allow void on captures and credits.

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#504]
Some gateways (e.g. CyberSource) support voiding captures and credits.

Test cases to add:

* AUTH, CAPTURE, VOID (capture), VOID (authorization)
* AUTH, CAPTURE, VOID (capture), CAPTURE

**Comment by sbrossie** [comment]
@pierre Should that be closed?

**Comment by pierre** [comment]
Not yet, I still need to merge the branch into 0.16.3.

**Comment by pierre** [comment]
Merged in work-for-release-0.16.3 as 5588436441bf9a2f163b7af0da799e1271fe2b71.

**Comment by sbrossie** [comment]
@pierre Re-opening issue and moving into 0.16.4. The new added [state machine transition](https://github.com/killbill/killbill/commit/5588436441bf9a2f163b7af0da799e1271fe2b71#diff-ce97f43836723498fe63c6cf531cbd60R481) from `VOID_SUCCESS` -> `CAPTURE_INIT` breaks our integration test [here](https://github.com/killbill/killbill-integration-tests/blob/master/killbill-integration-tests/core/test_payment.rb#L58)

So we should decide if the test needs to be changed but it seems to me like test is correct: i don't see why we would allow to do a `CAPTURE` after the initial `AUTH` was `VOIDED`. 

If this is the case, and if we really need to allow these transitions (what i am fearing) is that it shows the limitation of our state machine (more and more logic outside state machine to correctly enforce disallowed transitions)

**Comment by pierre** [comment]
> So we should decide if the test needs to be changed but it seems to me like test is correct: i don't see why we would allow to do a `CAPTURE` after the initial `AUTH` was `VOIDED`. 

Yup, this is a new bug (see also https://github.com/killbill/killbill/issues/514#issuecomment-210418947).

> If this is the case, and if we really need to allow these transitions (what i am fearing) is that it shows the limitation of our state machine (more and more logic outside state machine to correctly enforce disallowed transitions)

Indeed, I think the allowed transition logic is too simple in the automaton. We should take a pass at understanding and scoping the work involved to fix this.

**Comment by pierre** [comment]
> Indeed, I think the allowed transition logic is too simple in the automaton. We should take a pass at understanding and scoping the work involved to fix this.

After re-reading our code and looking at the default state machine, here are my findings and thoughts:

* Fixing https://github.com/killbill/killbill/issues/330 (per-plugin state machine) will help a lot. Here is the default state machine we have today:

![paymentstates](https://cloud.githubusercontent.com/assets/51940/15450875/3e0dd938-1f5f-11e6-9773-88b8b1c1b26b.png)

But the CyberSource state machine is much simpler:

![paymentstatescybersource](https://cloud.githubusercontent.com/assets/51940/15450901/e92fa652-1f5f-11e6-90c9-431d49fa92c1.png)

Same with the Adyen one:

![paymentstatesadyen](https://cloud.githubusercontent.com/assets/51940/15450923/7a26ad72-1f60-11e6-80dc-efdba93cbbc8.png)

* While the transaction-level state machine model is good, the code could be cleaned-up a bit (especially around when the context is populated and updated)
* What's really missing is conditions between transaction transitions (`linkedStateMachine`). See also https://github.com/killbill/killbill/issues/514. Maybe representing it as a [Mealy machine](https://en.wikipedia.org/wiki/Mealy_machine) would help:

![linkedpaymentmachine](https://cloud.githubusercontent.com/assets/51940/15451226/17250a5a-1f6c-11e6-962e-3db79b439b0d.png)


In the graph above, the notation `(I)/(O)` describes the input and associated output. The input is a tuple `(action, amount)` and the output is an accumulator representing the captured amount. The states `S` are virtual and don't necessarily map to the current XML states. The states `S2` (authorization reversed) and `S4` (partial or full refund) are terminal by (Kill Bill) convention. The transition through states simply update the accumulator after captures and refunds. The condition `capturedAmount == 0` makes the current state transition to `S1` (this solves https://github.com/killbill/killbill/issues/514). No assumption is made on the actual amounts (e.g. amount captured could be greater than the amount authorized) because it depends on the gateway and processor (this could be configured on a per plugin basis by slightly adapting our XML though). We could adapt the code to enforce this representation without changing the XML nor state on disk.

**Comment by sbrossie** [comment]
Few comments on the diagram above (by the way, the drawing helps a lot to continue the discussion):

1. I am not really convinced we need output values. What we really need however, is to modify our input so it also takes into consideration the capture amount (which we don't have today). Which means our input would become a triplet: `{action, plugin result, amount}`
2. In terms of state, we miss a `CAPTURE_SENT` and a `CAPTURE_SETTLED`, simply because those states are not available to us. The diagram above solves that problem by adding a condition `capture amount == 0` which brings us back to the `S1` state. However that condition is not really available in Kill Bill today (at a given time, we don't know what is the capture amount), and so when doing an `AUTH` after a `CAPTURE`, two things could happen:
  * The capture was not sent for settlement (and also for a particular gateway that supports it), and the `VOID` succeeds. However at this time we still don't really know to compute the capture amount and therefore we are not able to determine if we stay on `S3` or go back to `S1` (unless we had only one `CAPTURE`)
  * The `CAPTURE` was sent for settlement and the gateway will return an error (?, or at least something to indicate the `CAPTURE` was not `VOIDED`). In that case, we should stay in the same state `S2`.

**Comment by pierre** [comment]
Fixed as part of https://github.com/killbill/killbill/issues/330. See also https://github.com/killbill/killbill-integration-tests/commit/6180196fa70deaa8f7ed0157ae5c97781805ccbe.
