### ISSUE TITLE
InvoicePayment control plugin should be more resilient towards failures

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#508]
The invoice payment attempt should be created in the `priorCall` API and updated on the `onSuccess` API, so that in case the payment goes through but the machine crashes before `onSuccess` is called, we don't trigger a double payment  when re-trying.

**Comment by sbrossie** [comment]
Actually i don't think this is the case because when the `onSuccess` plugin callback fails, the payment code [does not fail the payment request](https://github.com/killbill/killbill/blob/killbill-0.16.3/payment/src/main/java/org/killbill/billing/payment/core/sm/control/ControlPluginRunner.java#L189) so there is payment retry.

However it is true that if we were to retry that payment manually we would end up with double payment so probably worth fixing anyways.
