### ISSUE TITLE
Change AccountResource.payAllInvoices should accept paymentExternalKey

### ISSUE THREAD

**Issue by almalki** [killbill/killbill#522]
we would like to track external payments using their references, no sure if this is also applicable to transactionExternalKey

**Comment by almalki** [comment]
@pierre what do you think, is this a valid use case and you would accept a PR?

**Comment by pierre** [comment]
Are you suggesting to be able to pass a `paymentExternalKey` and/or `transactionExternalKey ` (https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/JaxRsResourceBase.java#L397-L398) to `payAllInvoices`?

This is actually quite tricky because you don't know how many payments will be triggered in advance. What change are you thinking of?

**Comment by almalki** [comment]
@pierre My use case is simple: All payments we have are external, and amounts are not necessarily for single invoice, so the amount may cover multiple invoices and may also exceed and need to be added as credit to the account. We need to track these payments inside kill bill using their references (every external payment we receive has a reference), and we need to correlate payments inside kill bill with these external payments.

**Comment by pierre** [comment]
> the amount may cover multiple invoices

This won't work: Kill Bill assumes that a payment is associated with a single invoice (an invoice could have multiple partial payments though). Without it, you could end up in undetermined scenarios (for example, a partial payment for 2 invoices: is any of them fully paid?).

Did you take a look at [InvoiceResource#createInstantPayment](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L592)? Could you trigger one (external) payment per invoice?

**Comment by almalki** [comment]
@pierre 
I dont see how `createInstantPayment` is different from `payAllInvoices`, both generate random paymentExternalKey and random transactionExternalKey. I wanted to use `payAllInvoices` because it does pay all invoices starting from oldest to latest and if no more invoices it adds the remaining amount as credit. This combo call is very suitable for my case, except this paymentExternalKey problem.

**Comment by pierre** [comment]
> I dont see how `createInstantPayment` is different from `payAllInvoices`, both generate random paymentExternalKey and random transactionExternalKey. 

I overlooked that `createInstantPayment` doesn't let you specify external keys for the payment, that could be fixed easily though.

> I wanted to use `payAllInvoices` because it does pay all invoices starting from oldest to latest and if no more invoices it adds the remaining amount as credit. This combo call is very suitable for my case, except this paymentExternalKey problem.

If you want this logic and need to track individual payments (`payAllInvoices` will create N payments, and these N payments will have different external keys), you need to replicate this logic client-side (that's why I was suggesting to look at `createInstantPayment`).

**Comment by almalki** [comment]
createInstantPayment also does not accept paymentExternalKey, it uses createPurchaseForInvoice protected method which generates random paymentExternalKey.

**Comment by pierre** [comment]
Indeed, but that could be fixed easily though.

**Comment by javier-gomez-hs** [comment]
@pierre @sbrossie 
I can start working on this issue.
Could you add more details?
Thanks!

**Comment by pierre** [comment]
@javier-gomez-hs [InvoiceResource#createInstantPayment](https://github.com/killbill/killbill/blob/master/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L592) calls `createPurchaseForInvoice` which generates random UUIDs for both `paymentExternalKey` and `transactionExternalKey`.

`createInstantPayment` should respect the specified key in `InvoicePaymentJson` to populate these instead.

Note that when this method is called from `payAllInvoices` and `createPaymentMethod`, a random UUID still needs to be generated (as described above, the user cannot easily provide them since these methods will trigger N payments, not just 1).

For `createExternalCharges`, maybe we could let the user pass the `paymentExternalKey` and/or `transactionExternalKey` but only if all `createdExternalCharges` end up on the same invoice (otherwise we have the same issue). It seems like you would need a new query parameter though (and a change of the client java).

Does that make sense?

**Comment by javier-gomez-hs** [comment]
@pierre 
Yes it does!
I'll work on that.

Thanks!

**Comment by javier-gomez-hs** [comment]
@pierre @sbrossie 
I've finished with the code and created 3 different Pull Requests:
- [Kill Bill Core](https://github.com/killbill/killbill/pull/584)
- [Kill Bill Client Java](https://github.com/killbill/killbill-client-java/pull/41)
- [Kill Bill OSS Parent](https://github.com/killbill/killbill-oss-parent/pull/7)

Please feel free to review them and let me know if I have to change anything else.

Thanks!
