### ISSUE TITLE
CatalogUserApi#uploadCatalog should validate catalog

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#531]
`CatalogResource#uploadCatalogXml` already validates the catalog today, before storing it. `CatalogUserApi#uploadCatalog` does not though, which can corrupt the cache if a bad catalog is uploaded in a plugin for instance.

**Comment by sbrossie** [comment]
If i understand correctly the fix is to move the validation inside the `CatalogUserApi#uploadCatalog` api (which i agree would make sense). The part i am less clear about is what triggered that issue? It seems `CatalogUserApi#uploadCatalog`  is only used from `CatalogResource#uploadCatalogXml`. Or is to support use cases where plugin would invoke that api?

**Comment by pierre** [comment]
Yup, IIRC, the use-case from the mailing-list was a call from a custom plugin.
