### ISSUE TITLE
Upgrade ehcache to caffeine?

### ISSUE THREAD

**Issue by anandchida** [killbill/killbill#532]
Caffeine based on java 8 is gaining a lot of popularity - https://github.com/ben-manes/caffeine

https://github.com/ben-manes/caffeine/wiki/Benchmarks

Can killbill take advantage of this cache?

**Comment by pierre** [comment]
Not today, as we need to keep support for Java 6 and 7.

Are you having performance issues with Ehcache?

**Comment by ben-manes** [comment]
While I'm not a fan of [jsr107](http://www.javadoc.io/doc/javax.cache/cache-api/1.0.0), that might be a reasonable target. `CacheController` seems simple enough to proxy to their api. You'd have to rely on the vendor configuration file since the programmatic configuration is too weak. Then users could choose whatever backend they wanted.

Whether you gain any benefit from the improved concurrency / hit rate would require measuring.

**Comment by ben-manes** [comment]
I noticed #587 and strongly recommend that you performance test when changing caching providers / major versions. Ehcache 3.0m5 switched to the MRU policy, which tends to result in extremely poor hit rates. Previously they used LRU, but decreased the quality of sampling compared to 2.x resulting in degraded hit rates (MRU-heavy distribution). The choice of forcing MRU appears to be retained in the latest v3.1.1 and results in a 10pt decrease compared to the previous version in most of my application traces. Note that if you acquire a trace we could easily [simulate](https://github.com/ben-manes/caffeine/wiki/Simulator) it and you can ensure the test code is honest.

In fairness MRU can perform better than LRU, e.g. in scan heavy workloads, but it is not the common case. Their decision to switch policies did not appear to be for technical reasons.
