### ISSUE TITLE
Wrong updated_date in update queries

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#540]
See https://github.com/killbill/killbill/blob/master/payment/src/main/resources/org/killbill/billing/payment/dao/TransactionSqlDao.sql.stg#L68 for example.

**Comment by sbrossie** [comment]
@pierre I updated the SQL to use correct field from context, but i think this is not enough: This context is often created all the way up from JAXRS and both `createdDate` and `updatedDate`[ are set with the same value](https://github.com/killbill/killbill/blob/master/api/src/main/java/org/killbill/billing/callcontext/DefaultCallContext.java#L44).

In order to cleanly fix the issue we would need recreate a new context each time we need set the `updatedDate`. As an alternative we could hack our [InternalTenantContextBinderFactory](https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/callcontext/InternalTenantContextBinder.java#L71) to always have `updatedDate` = `Clock,getUTCNOW()`, but even that in not so easy as the `Clock` is not available.
