### ISSUE TITLE
Catalog defines a `plansAllowedInBundle` but does not seem to be used

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#545]
I am also not quite sure about the semantics. I believe that would define how many subscription of a particular `Plan` could exist within the same bundle.

**Comment by sbrossie** [comment]
The XML model already supports limiting how many subscriptions of a particular `Plan` (and for a given bundle) can be created, but this has not been implemented.

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
Hi guys! I've started working on this issue and I was wondering if this is expected to happen only with **ADD_ON** products / plans?
I think so, because when a **BASE** product is used to create an entitlement, the `bundleId` is not being taken into account. Am I right?

Thanks!!

**Comment by sbrossie** [comment]
@javier-gomez-hs  Yes you are correct, The `plansAllowedInBundle` basically restricts the number of ADD_ON subscriptions of a specific kind that can be created within a given bundle.

**Comment by javier-gomez-hs** [comment]
@sbrossie 
Thanks for the info!
Just to confirm: I should add the restriction not only when a new ADD_ON subscription is being created, but also when an existing ADD_ON subscription changes its Plan / Product, right?
For example:
**ACCOUNT** has a base **SUBSCRIPTION** "SA" with 3 **ADD_ONs**: A1, A2 and A3.
A1 and A2 are **ADD_ONs** of the same plan, and A3 has a different plan.
The limit (`plansAllowedInBundle`) is **2**.
Now the user tries to change the A3 **ADD_ON**, to match the same plan of A1 and A2.
Due to the limitation of 2, it should **reject the change** with an exception.
Is that right?

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-hs Yes this is correct.

**Comment by javier-gomez-hs** [comment]
I have created the first approach:
- killbill-core: https://github.com/killbill/killbill/pull/609
- killbill-api: https://github.com/killbill/killbill-api/pull/21
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/13

Please feel free to take a look and let me know if there is something wrong.

Thanks!

**Comment by javier-gomez-hs** [comment]
@sbrossie 
The same limit should exist when trying to create a new Subscription with AddOns in a single transaction with [this](https://github.com/javier-gomez-hs/killbill/blob/99b11adc0cdaf4279838e89cb7d64fc4ab87e027/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/SubscriptionResource.java#L287) method, right?
I'll need to inject the CatalogUserApi in order to get the current catalog's available addons for the base Entitlement, and check the `plansAllowedInBundle` from there, because the bundle has not been created yet.
If the ADD_ONs in the list are from the same plan, and the number is higher than the `plansAllowedInBundle` value, should I reject the whole creation (entitlement + addons) with an exception? Or just let the application create partially the entitlement with the allowed addons?

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-hs yes  you are correct that the bulk creation should also enforce the `plansAllowedInBundle`, but i would not make the check at the JAXRS level. I think all those checks should belong to the low level subscription module (where catalog has already been injected). In that specific use case, this would happen [here](https://github.com/killbill/killbill/blob/work-for-release-0.17.x/subscription/src/main/java/org/killbill/billing/subscription/api/svcs/DefaultSubscriptionInternalApi.java#L204).

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
Guys, I've finished with my code but before pushing the changes I wanted to confirm that all Integration tests are still working.
For my surprise, there was one test failing [here](https://github.com/javier-gomez-hs/killbill/blob/d43300589a4c31409d1fdabf2f58a4d29b3f4157/entitlement/src/test/java/org/killbill/billing/entitlement/engine/core/TestEntitlementUtils.java#L326-L326), so I decided to investigate a little bit and I found [this](https://github.com/javier-gomez-hs/killbill/blob/32349864eab48fd62cd65673b6495460cbe2a0af/catalog/src/main/java/org/killbill/billing/catalog/DefaultPlan.java#L74-L79).
Setting it by default to 1 is making that test fail, because it is trying to add 2 add_ons with the same plan, and the limit (if not specified) is 1.

I wanted to know your thoughts about that. I know that this wasn't working before but now I want to make sure that the default value is 1 and the unlimited value is -1.
In that case I will need to change some test to match the new limits.

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-hs I would change the default limit to be unlimited (that would keep it consistent with what we had before, since this was not implemented), and so as a side effect tests should still pass in their current form.

**Comment by javier-gomez-hs** [comment]
@sbrossie 
I've finished with the code.
Would you be able to take a look at the changes?

- killbill-core: https://github.com/killbill/killbill/pull/609
- killbill-api: https://github.com/killbill/killbill-api/pull/21
- killbill-oss-parent: https://github.com/killbill/killbill-oss-parent/pull/13

Please let me know if I have to change anything else.

Thanks!
