### ISSUE TITLE
Catalog string names need to be unique across all objects

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#569]
When specifying plan names, usage section names, price list names, ... one needs to carefully make sure all those strings are unique. Also there are some limitations in the character set (TBD) which caused some confusion in the past.

**Comment by beccagaspard** [comment]
Not sure if it belongs with this issue or not - but it would be great if you could specify a "display name" for products, plans, pricelists, etc.  The allowed formatting in the catalog xml is pretty limited (no spaces allowed) and it would great to be able to change the display name without affecting the underlying system - a good example might be if a product was rebranded to a new name.

**Comment by pierre** [comment]
@beccagaspard FYI, we did this for the Overdue system XML, which lets you configure the message to display to the user as `externalMessage`, but we came to regret it. The problem is that it's not easily _internationalizable_ (tracked by https://github.com/killbill/killbill/issues/63). So while I 👍 the feature, we don't quite know yet how to implement it.

**Comment by sbrossie** [comment]
The unicity of the strings comes from the JAXB implementation which imposes each object (in the model) to have a unique string (`@XmlID`). See #580.

We are not planning to address that anytime soon, so closing the issue. Note that we did work on catalog validation (See #678) which should help alleviate issues with loading bad catalog.
