### ISSUE TITLE
Catalog serialization formatting is broken

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#579]
When doing a catalog serialization most of the XML generated is correctly formatted except for a few sections (and this is a bit annoying). Example:

```
    <plans>
        <plan name="standard-annual">
            <product>Standard</product>
            <initialPhases>
                <phase type="TRIAL">
                    <duration>
                        <unit>DAYS</unit>
                        <number>30</number>
                    </duration>
                    <fixed type="ONE_TIME">
                        <fixedPrice>
                            <price>
<currency>USD</currency>
<value>0</value>
                            </price>
                            <price>
<currency>GBP</currency>
<value>0</value>

```

**Comment by matias-aguero-hs** [comment]
@sbrossie how we can reproduce it?

**Comment by sbrossie** [comment]
@matias-aguero-hs A quick way to see is to enable the [commented printf in that test](https://github.com/killbill/killbill/blob/killbill-0.17.2/catalog/src/test/java/org/killbill/billing/catalog/io/TestXMLWriter.java#L60)

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
Hi guys, I started investigating about this issue and after some tests and readings, I found out that **JAXB** has a limitation of 8 levels of indentation when is marshalling a file. Once it reaches level 9, it starts back to level 0 (which is our exact case).
This bug is still unresolved [here](https://java.net/jira/browse/JAXB-970). 

What do you think about this?
Should we try to marshal / unmarshal the XML file with any other tool? I'm open to any suggestion.

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-hs I would not bother, let's skip it for now.
