### ISSUE TITLE
External Charge new invoice is not published to the notification plugin

### ISSUE THREAD

**Issue by MusharrafSakran** [killbill/killbill#592]
When creating an external charge without attaching it to an existing invoice the system will generate a new invoice for this external charge item. the problem is that, the new generated invoice is not getting published to the notification plugin in order to consume it under this event type:
[ ExtBusEventType.INVOICE_CREATION ].

the expected behavior is that the new generated invoice should be published to the notification plugin as new invoice created.

this issue is exists in version # 0.16.2
thanks.

**Comment by sbrossie** [comment]
Musharraf,

The behavior is indeed incorrect, and the issue has been fixed in our
current 0.17.x branch. For 0.16.x release, you should be able to catch the
change by listening to INVOICE_ADJUSTMENT event.

Let me know if this is not the case,

Stéphane


On Wed, Aug 3, 2016 at 9:36 AM, Musharraf AlTamimi <notifications@github.com

**Comment by MusharrafSakran** [comment]
Ok it is working now with INVOICE_ADJUSTMENT event. 

thanks a lot. I'll close the issue
