### ISSUE TITLE
Complete payment transaction may end up two payment transactions

### ISSUE THREAD

**Issue by daliwei** [killbill/killbill#660]
In case of HPP payment process such as PayPal, the first transaction was created as pending status. Then, the complete authorization call comes in when the first transaction status is still `PENDING`. However, during this process, the Janitor is invoked and transitioned the pending payment to failure (e.g., token expired after a pre-defined time period), then the `LeavingAuthorizeOperation` will create a new payment transaction with the same external key instead of reuse that failed payment transaction. 

One of the solution is to fail the operation if the pending transaction is transitioned to failure after Janitor is invoked.

**Comment by sbrossie** [comment]
@daliwei Is that reproducible? I think a new payment test would be ideal to really understand and fix the issue.

**Comment by daliwei** [comment]
@sbrossie Yep. I think it is reproducible. I will come up with a test to demonstration this issue.

**Comment by pierre** [comment]
By design, payment and transaction external keys can be re-used on new payments or transactions, if the original payment or transaction wasn't successful. This is especially useful for payment retries: a payment will be associated with multiple transactions (all sharing the same transaction external key and typically in a `PAYMENT_FAILURE` status). Each of these transactions will be associated with an attempt in a `RETRIED` state.

In this case, after the state has been fixed (during the completion) from `PENDING` to `PLUGIN_FAILURE`, the completion behavior is the same as if one was trying to re-attempt the authorization on that same payment, with the same transaction external key.

The expected behavior would be that the payment would now have 2 transactions, both with the same external key and both in `PLUGIN_FAILURE`.

It sounds like what you see instead is a payment with 2 transactions, both with the same external key but the first one in `PLUGIN_FAILURE` and the second one `PROCESSED`. This is a valid state if the subsequent attempt was successful.

In case of PayPal specifically however, if the token is expired, the subsequent payment attempt cannot go through, so I would expect the plugin to return `PLUGIN_FAILURE` after trying to use that token in PayPal. Isn't it a bug in the plugin? Could it be that the token expiration period configured in the plugin (3 hours by default) doesn't match the period configured in the merchant account? In that case, Kill Bill would proactively cancel the payment but the token being still valid a little while longer, the payment would go through if attempted.

**Comment by daliwei** [comment]
Thanks for the explanation!

> In case of PayPal specifically however, if the token is expired, the subsequent payment attempt cannot go through, so I would expect the plugin to return PLUGIN_FAILURE after trying to use that token in PayPal. Isn't it a bug in the plugin? Could it be that the token expiration period configured in the plugin (3 hours by default) doesn't match the period configured in the merchant account? In that case, Kill Bill would proactively cancel the payment but the token being still valid a little while longer, the payment would go through if attempted.

This issue can happen in the following hypothetical setting:
1) Janitor intervals: 5m, 1hr
2) Token expiration time set in the PayPal plugin: 1 hr 
3) "Real" expiration time with PayPal merchant account say 2hs

When the complete_auth request hits KB at say 1hr 2m after the build_form_descriptor, then it first invokes Janitor and Janitor will set the payment to `PLUGIN_FAILURE` (1hr > 1hr2m). However, the call will still go through and succeed at PayPal. Is that the expected behavior?

**Comment by pierre** [comment]
> 2) Token expiration time set in the PayPal plugin: 1 hr 
> 3) "Real" expiration time with PayPal merchant account say 2hs

Exactly -- and I think that's the root cause. I don't understand why these two settings would be different (the expiry time is configurable in the plugin IIRC).

> When the complete_auth request hits KB at say 1hr 2m after the build_form_descriptor, then it first invokes Janitor and Janitor will set the payment to `PLUGIN_FAILURE` (1hr > 1hr2m). However, the call will still go through and succeed at PayPal. Is that the expected behavior?

Kill Bill doesn't understand anything about PayPal and expired tokens. It sees the payment with a first transaction unsuccessful (`PLUGIN_FAILURE` -- could be that the gateway is down) and a subsequent attempt as successful (maybe the gateway is back?).

It sounds like the plugin is misbehaving and/or misconfigured. It should:

* Align the configured expiry time with the real one in PayPal
* And/Or check if the token is "softly" expired (on our end) before attempting to use it

**Comment by daliwei** [comment]
>Exactly -- and I think that's the root cause. I don't understand why these two settings would be different (the expiry time is configurable in the plugin IIRC).

It may happen when we intentionally set a different expiry time than the allowable maximum one (e.g., we don't want to hold the inventory too long to wait for the user's completion).

>It sounds like the plugin is misbehaving and/or misconfigured. It should:
Align the configured expiry time with the real one in PayPal
And/Or check if the token is "softly" expired (on our end) before attempting to use it

Given that we might intentionally set a shorter expiry time, the second approach seems to be more appealing.

**Comment by pierre** [comment]
> It may happen when we intentionally set a different expiry time than the allowable maximum one (e.g., we don't want to hold the inventory too long to wait for the user's completion).

Gotcha, that makes sense.

> Given that we might intentionally set a shorter expiry time, the second approach seems to be more appealing.

Agreed, I've created https://github.com/killbill/killbill-paypal-express-plugin/issues/22 for tracking.
