### ISSUE TITLE
Implement automatic invoice Draft mode

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#662]
Kill Bill is a very reactive system: A user will typically create a subscription, which will generate an bus event that will be handled by invoicing system to create an invoice, and then the payment system will listen and also create a payment (... + overdue system,...).

Kill Bill allows specific `Account` to be tagged with `AUTO_INVOICING_OFF` or `AUTO_PAY_OFF` to disable that automatic mode, but there are situations where we would like that implemented at the tenant level:

* Business use case:  One may want to review invoice generation prior the payment gets automatically applied
* Bug in the system: We want to make sure subscriptions can still be processed, but no invoice is being generated for the whole tenant (until issue gets fixed)

**Comment by sbrossie** [comment]
One simple way to achieve that goal would be to add a tenant level invoice configuration to automatically create invoices in `DRAFT` mode (payment system would not attempt payment, overdue system would not mark account as being overdue because invoice balance shows as $0).

In addition to the config, we would need to easy the review of such `DRAFT` invoices (maybe new endpoints) and potentially couple that with some KAUI work to review and commit a bunch of such invoices by batch.

**Comment by sbrossie** [comment]
A more complex implementation (that could be an extension of what was described previously) would be to introduce the notion of batches to isolate different accounts (good one, problematic ones,...)

**Comment by pierre** [comment]
Implementing the automatic `DRAFT` mode is more complicated than initially thought:

* What happens to the `DRAFT` invoice after a subsequent invoice run? Should we update that invoice or create a new one?
* Related to this, should we try to respect bundling of subscriptions (BCD) and generate several `DRAFT` invoices or always combine everything on the latest one?
* What's the impact on manual `DRAFT` invoices? HA?

Because of these non-trivial questions and potential large changes in the system, this task is too big for the 0.18.x release train.

To solve the two use-cases (ability to manual review and workaround bugs in the system) mentioned above, implementing a batch mode could be easier:

* A batch is defined by its name and schedule (frequency -- could be `NEVER` for problematic accounts -- and what time in the day it should run)
* New tables and API would let a user CRUD batches and add accounts to batches. Configuration could be set to have a default batch for a given tenant
* New APIs would let the user manually execute a batch and run a dry-run
* Regarding the implementation, the main logic to change would be to change the date when computing the notification queue entry (currently computed by the system, determined by the batch configuration in the new mode). A notification entry would also be created (if needed) to react on bus events. One challenge though might be to move accounts in/out batches, to make sure we don't miss any future notification date

While this approach is simpler in many respects (e.g. no side-effect state on disk), this is still too complex to solve the immediate use-cases mentioned above. Instead, we've decided to not solve case 1. for now (i.e. being able to review invoices before they post). Instead, we just want to make sure there is a safety switch for the invoicing system in case we need it.

As a result, we will only implement a system level shutoff switch for the invoicing system. The notification queue will essentially be off and bus events will simply result in new entries written in the queue (available `now()`).

**Comment by pierre** [comment]
> The notification queue will essentially be off and bus events will simply result in new entries written in the queue (available `now()`).

We've decided to park accounts instead due to how the notification queue is implemented (main dispatching thread will claim across all queues). This is also more flexible (can be turned on/off at runtime, per tenant).
