### ISSUE TITLE
Hardening for bad state

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#664]
Recently, we have implemented #26 to disable invoice generation in case where system realize that we created too many invoices for a given subscription on a given date.

The goal of this task is to expand on that work:
* Add similar logic but to detect creation of similar items for a given subscription (with lower bound value)
  * `RECURRING` with same `startDate` and `endDate`
  * `FIXED` with same `startDate` 
* Create a new system tag to move 'broken' accounts (disable invoicing/payment) on such accounts. The tag can only be set from within system but can be removed through api (after state was fixed).

**Comment by pierre** [comment]
> Create a new system tag to move 'broken' accounts (disable invoicing/payment) on such accounts. The tag can only be set from within system but can be removed through api (after state was fixed).

I'd like to push back on this for now because of the complexity:
* API change (`ControlTagType` enum) is painful to propagate to plugins
* `AutoPayOff` and `AutoInvoicingOff` are attributes of control tags, which would have consequences on various systems. For example:
  * `InvoicePaymentControlPluginApi` would enter these accounts into the `_invoice_payment_control_plugin_auto_pay_off` table (because the tag has the attribute) but never process them later (it processes only the removal of the `ControlTagType.AUTO_PAY_OFF` tag).
  * Junction will not return any `BillingEvent` anymore if the `AutoInvoicingOff` attribute is set, so we would not be able to trigger any invoice generation manually to verify the state is fixed (and if the administrator removes the tag to try, an event will be sent to the system, potentially triggering events automatically before he can try a dry-run generation)

Additionally, I am wondering if it could be solved by https://github.com/killbill/killbill/issues/662 instead (i.e. batches).

**Comment by pierre** [comment]
Here's what we've decided:

* Create an invoice specific internal (yet user) tag for accounts: `__PARK__`. Because it is a user tag, no API change needed and no issue regarding confusing attributes. On a related note, we might consider introducing other internal, subsystem specific, user tags in the future. Creating uppercased user-defined tags are prohibited through the API, so there shouldn't be any conflict with real user tags. Additionally, because they won't leak in the API, plugin implementors won't be tempted to use them.
* The tag will be set automatically by the system to any problematic account and removed if a subsequent invoice dry-run succeeds. Requests to generate non dry-run generations will fail.
* _problematic_ is defined as any illegal state detected by the tree or bounds triggered. Note: for the latter, in case bounds are triggered and the user decides to bump the threshold, a dry-run generation will be required to remove the tag (e.g. catch-up scenario).
