### ISSUE TITLE
Display payment retry in billing timeline

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#69]

**Comment by pierre** [comment]
See also discussion here: https://github.com/killbill/killbill/issues/393.

**Comment by sbrossie** [comment]
True but #393 has been closed so this bug tracks the specific piece about exporting the payment retries. I think this is a nice feature to have.

**Comment by pierre** [comment]
:+1: (I just wanted a link to your description of how retries work)

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
I've been testing this issue, and as far as I saw, all the payment retries are being added to the **Account Timeline** with the status: "PAYMENT_FAILURE":
![image](https://cloud.githubusercontent.com/assets/16122005/16128355/cc422e8a-33d6-11e6-8695-1ccd9ce08167.png)

(I have added the **payment-test** plugin in order to simulate the payment failures)

Is this the expected behavior? 
When you say "Billing Timeline" you meant the "Account Timeline"?

> this bug tracks the specific piece about exporting the payment retries. I think this is a nice feature to have

I'm not sure what do you mean with exporting the payment retries.

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-hs I would suggest to hold on on this task. We have a task on our end to revisit our story about payment retries and i think this will overlap with that work. I'll sync up with @pierre in the near future, to see if there is anything you could do on your end.

**Comment by pierre** [comment]
Regarding this task, I think the original bug was to display the failed retries in the timeline. As @javier-gomez-hs pointed out, this has been fixed.

What's missing though (originally part of https://github.com/killbill/killbill/issues/393) is seeing the scheduled retry on the invoice (or payment) page.

Something like this would be nice:

![image](https://cloud.githubusercontent.com/assets/51940/16312960/db648d40-392b-11e6-91ab-09d6906eb5c6.png)

If there is no scheduled retry, this would implicitly mean that we gave up retrying.

To implement this though, we need a new API exposing the attempts. [Thinking out loud] Maybe something like `GET /1.0/kb/payments/<paymentId>/attempts?includeFuture=false` (and variations with keys like  `GET /1.0/kb/payments/attempts?paymentExternalKey=XXX&includeFuture=false`). When `includeFuture` is true, the code would need to search the `payment-service` queue for scheduled retries.

**Comment by javier-gomez-hs** [comment]
Yes @pierre, it does make sense!
I'll work on that and let you know when it's done.

Thanks for your help!

**Comment by javier-gomez-hs** [comment]
@pierre @sbrossie 

I've created 2 Pull Requests with my changes:
- [This one](https://github.com/killbill/killbill-api/pull/15) for **killbill-api**
- [This one](https://github.com/killbill/killbill/pull/564) for the **core**

Please note:
- I've updated the **killbill-oss-parent** version in the pom.xml of the **core**, in order to use the updated version of **killbill-api** (the one that includes my changes in the other PR). This change must be done in the **killbilll-oss-parent** project. Should I create a new Pull Request with that change?
- Some changes should be done in the **Java** and **Ruby** **clients** to use this new attribute.
- Some changes need to be done in **KAUI** in order to get the new JSON parameter and show it properly as part of the Transactions table.

Please let me know if you think I should change anything.

Thanks!

Javier.

**Comment by javier-gomez-hs** [comment]
@sbrossie @pierre 
I've created new Pull Requests with the changes of this issue and https://github.com/killbill/killbill/issues/163. All of them are pointing to the **work-for-release-0.17.x** branch:

- Kill Bill (Core): https://github.com/killbill/killbill/pull/576
- Kill Bill OSS Parent (0.113-SNAPSHOT): https://github.com/killbill/killbill-oss-parent/pull/6
- Kill Bill API (0.39-SNAPSHOT): https://github.com/killbill/killbill-api/pull/17
- Kill Bill Client (0.29-SNAPSHOT): https://github.com/killbill/killbill-client-java/pull/40

All Integration tests are passing. Please feel free to take a look and let me know if I have to change anything else.

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-hs Do you have a plan to also change KAUI? Are you working with ruby as well?

**Comment by javier-gomez-hs** [comment]
@sbrossie
Honestly, I don't have experience working with ruby, but if you want I can take a look at the code. Maybe it is easy to add the new scheduled items.
