### ISSUE TITLE
Overdue - subscriptionCancellationPolicy END_OF_TERM works as IMMEDIATE

### ISSUE THREAD

**Issue by petrkoshkin** [killbill/killbill#698]
killbill version 0.18.2
I use killbill-overdue-0.18.3.jar (built from master) with NullPointer issue https://github.com/killbill/killbill/issues/687 fixed.

Overdue configuration is the same as specified in the tutorial: http://docs.killbill.io/0.18/overdue.html

According to this tutorial: "subscriptionCancellationPolicy is set to END_OF_TERM to indicate that subscriptions should be cancelled in such a way that we do not generate credit for the account (no proration)"

But when killbill enters CANCELLATION state all subscriptions are cancelled immediately and proration happens (which is not expected).

**Comment by sbrossie** [comment]
@petrkoshkin Could you report issues on the mailing list instead of filing bugs (i'd rather we do that ourselves).


Now regarding the issue you described, i did write a test case to test the `END_OF_TERM` policy when i fixed the NPE you reported in #687. The test seems [to indicate that billing `END_OF_TERM` cancellation occurs correctly](https://github.com/killbill/killbill/blob/master/beatrix/src/test/java/org/killbill/billing/beatrix/integration/overdue/TestOverdueWithSubscriptionEOTCancellation.java#L106)

**Comment by petrkoshkin** [comment]
@sbrossie, If you want me to report the issues on mailing list I will definitely do this way.

Regarding the issue: I tried this use case from the beginning manually five times and issue was reproduced all the times.
What I observe just after transferring to the CANCELLATION state is killbill makes adjustment (subscription change) with minus sign in such a way that some part of invoice payment (exactly that part when subscription was in BLOCKED state) is returned to the account's credit with plus sign.

**Comment by sbrossie** [comment]
Could you export your accountData
<https://github.com/killbill/killbill/wiki/Production-troubleshooting#exporting-account-data>
and send it to me?

**Comment by petrkoshkin** [comment]
Sure, 
[account_b5cb07e5-5db2-44f6-b7c3-9e5ddeaf8ee9.data.zip](https://github.com/killbill/killbill/files/726382/account_b5cb07e5-5db2-44f6-b7c3-9e5ddeaf8ee9.data.zip)

**Comment by sbrossie** [comment]
Ok, i looked at your data:
* On `2017-03-11` the overdue `BLOCKED` kicks-in. Because config set `disableEntitlementAndChangesBlocked` to true-- terrible name, i must admit--, billing will also be blocked starting from that date
* On `2017-03-18` the overdue state in `CANCELLATION`. Here it gets tricky:
** From en entitlement point of view, subscription is cancelled on  `2017-03-18` (service to user should be disabled). But because config does not specify `disableEntitlementAndChangesBlocked` to true the `block_billing` flag from `blocking_states` is set to 0
** From a billing point of view, the subscription gets cancelled on `2017-03-24`, which is `END_OF_TERM `, as specified by the config.

So, based on this configuration, code works as expected, it blocks the period `2017-03-11` -> `2017-03-18`, but probably this is not what you expected (and probably we should update our doc):


@petrkoshkin Could you try to remove `disableEntitlementAndChangesBlocked=true` for `BLOCKED` phase (and then billing should really happen EOT with no blocking period) ?

**Comment by petrkoshkin** [comment]
@sbrossie Thank you very much for the explanation! I really thought that disableEntitlementAndChangesBlocked should affect only entitlement and not billing. Now I understand that it was wrong expectation. Removing of disableEntitlementAndChangesBlocked=true and addressing blocking of entitlement in a separate event listener solves the issue. Thank you for your help :+1:

**Comment by sbrossie** [comment]
Yeah our naming is terrible (but changing it is tricky for users that already have a config in place). I will update our overdue doc to remove this setting. Thanks for your patience and the report.
