### ISSUE TITLE
Account balance should not take into account DRAFT invoices

### ISSUE THREAD

**Issue by pierre** [killbill/killbill#749]
A credit on an invoice still in `DRAFT` mode for instance is taken into account when computing the account balance.

**Comment by sbrossie** [comment]
The issue is that the [computation of the CBA](https://github.com/killbill/killbill/blob/killbill-0.18.8/invoice/src/main/java/org/killbill/billing/invoice/calculator/InvoiceCalculatorUtils.java#L181), which is then used to [compute the account balance](https://github.com/killbill/killbill/blob/killbill-0.18.8/invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java#L443) does not take into account the `DRAFT` invoices.

We need to be cautious when making the change to understand at which level we want to filter those `DRAFT` invoices. We have a few layers and a few dimensions:

For `Invoice#balance` computation the `DRAFT` invoices are filtered at the highest level inside the `DefaultInvoice` [implementation](https://github.com/killbill/killbill/blob/killbill-0.18.8/invoice/src/main/java/org/killbill/billing/invoice/model/DefaultInvoice.java#L249). Also attributes such as `writtenOff` and `isMigrated` are also controlled from the caller to the [implementation method](https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/calculator/InvoiceCalculatorUtils.java#L75).

For `Account#balance` -- which takes into consideration `CBA`-- we don't exclude things the same way.

We need to clarify where `DRAFT`, `isMigrated` and `writtenOff` attributes matter, and where in the implementation chain (`DefaultInvoice` v.s `/DefaultInvoiceDao`,  `InvoiceModelDaoHelper `,`InvoiceCalculatorUtils` )such attributes are considered.
