### ISSUE TITLE
Ability to change a registered user's currency.

### ISSUE THREAD

**Issue by JulianChow94** [killbill/killbill#756]
Whenever i use a PUT request to attempt to update a registered KillBill account to a new currency i get the following error response

```
{
  "className": "java.lang.IllegalArgumentException",
  "code": null,
  "message": "Killbill doesn't support updating the account currency yet: new=USD, current=CAD",
  "causeClassName": null,
  "causeMessage": null,
  "stackTrace": []
}
```

On my system, a user's currency & payment method has a 1-1 mapping with their current country. When one of my users changes countries, I would like to have the ability to update their corresponding kill bill account to their new country's currency.

**Comment by pierre** [comment]
> When one of my users changes countries, I would like to have the ability to update their corresponding kill bill account to their new country's currency.

This is currently not supported, and probably won't be in the near future due to the extra complexity needed to manage things like account credits (which could now span across multiple currencies).

A work-around would be to create a new account with the new currency, and re-create (or transfer) subscriptions.

Moving forward, please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) for implementation questions.
