### ISSUE TITLE
API POST /tagDefinitions doesn't take into account applicableObjectTypes

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill#759]
The POST /tagDefinitions API doesn't seem to take into account the applicableObjectTypes parameter, which creates a tag applicable to any kind of object.

A request like this:
```
{"id":null,"isControlTag":null,"name":"abcdef","description":"Lorem","applicableObjectTypes":["INVOICE"],"auditLogs":null}
```
currently generates a tag definition like this:
<img width="1158" alt="capture d ecran 2017-05-30 a 01 51 12" src="https://cloud.githubusercontent.com/assets/3975044/26563930/82384e94-44da-11e7-8c82-022530109c3c.png">

Is there a reason for this?

**Comment by pierre** [comment]
> Is there a reason for this?

It was probably setup that way because these control tags are ignored by the system, but I don't think there is a strong reason for it.

We could enhance the API to take `applicableObjectTypes` into account, and add validation when a user adds such a tag.

Tracking it in our `Release-0.20.0` milestone for consideration (requires DDL + API change).
