### ISSUE TITLE
Extend custom field apis to support update operation

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#803]
In the current model, the user needs to delete and then recreate such custom field.

**Comment by sbrossie** [comment]
/cc @pierre While looking at this issue, i read the current implementation for adding custom fields, a few things came to mind
1. The code is [quite complex ](https://github.com/killbill/killbill/blob/killbill-0.18.13/util/src/main/java/org/killbill/billing/util/customfield/api/DefaultCustomFieldUserApi.java#L91), because we don't have unique constraint in our DDL so we have to do everything by hand in code. I think having a unique constraint on {`object_id`,`object_type`,`name`, `tenant_record_id`} would make sense and would avoid all the complexity -- we could probably omit `object_type`, and even `tenant_record_id` since we expect our UUID to be unique across all namespaces.
2. At this point making the code transactional becomes easier
3. And then implementing the update could be one batch delete following by one batch insert into one transaction.

**Comment by pierre** [comment]
> I think having a unique constraint on {`object_id`,`object_type`,`name`, `tenant_record_id`} would make sense and would avoid all the complexity -- we could probably omit `object_type`, and even `tenant_record_id` since we expect our UUID to be unique across all namespaces.

Adding a unique index makes sense, although I believe we don't typically rely on DDL constraints to propagate such errors back to the user: we always do some amount of checking in the code, like [here](https://github.com/killbill/killbill/blob/1bb65997ac1c4371078e7e290acb86d27aa06744/util/src/main/java/org/killbill/billing/util/entity/dao/EntityDaoBase.java#L61-L63) (by original design choice, but also because catching the exceptions is not always easy, see https://github.com/killbill/killbill/issues/34).

> And then implementing the update could be one batch delete following by one batch insert into one transaction.

👍

**Comment by pierre** [comment]
@sbrossie Was this closed on purpose?

**Comment by sbrossie** [comment]
@pierre Closed by mistake, re-opening...
