### ISSUE TITLE
Janitor updates payment in wrong status

### ISSUE THREAD

**Issue by unieagle** [killbill/killbill#809]
https://github.com/killbill/killbill/blob/1bb65997ac1c4371078e7e290acb86d27aa06744/payment/src/main/java/org/killbill/billing/payment/core/janitor/IncompletePaymentTransactionTask.java#L175-L180

Hi @pierre @sbrossie ,

**The issue**
From some refund failures, we've located a bug in Janitor.
In short, the `paymentTransaction` is refreshed outside the account lock in the above codes. This caused in some case (~<1 in 1000) that when Janitor acquired the lock, the `paymentTransaction` has already changed the status by other threads.

**An example**
Here is an example timeline of this bug:
1. host3 get a combo call;
2. host3 enter auth
3. host1 refreshing analytics data for this account
4. host3 auth completed, updated the payment status to `AUTH_SUCCESS`
5. host7 get a capture call, and finished in payment status changed to `CAPTURE_SUCCESS`
6. host1 updated the auth status to `PROCESSED` again and updated payment status back to `AUTH_SUCCESS`

So the host1 finally executed the code above but which actually should not.

**Fixing proposal**
I think simply refresh the `paymentTransaction` from the `paymentDao` again above line 178 will fix this bug.

**Comment by sbrossie** [comment]
@unieagle  Could you describe wha ends up being wrong: Is that the `transaction_status` associated to the AUTH `PaymentTransaction`, or the `state_name and `last_success_state_name` associated with the `Payment`, or both. If the issue is solely with the `PaymentTransaction`,  is that relevant to include in the example above the capture call that occurs on host7 ?

**Comment by unieagle** [comment]
the payment `state_name` end up with `AUTH_SUCCESS` is wrong, should be `CAPTURE_SUCCESS`.
