### ISSUE TITLE
Improve catalog usage validation

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill#886]
This was reported on the [mailing list](https://groups.google.com/forum/#!searchin/killbilling-users/prem%7Csort:date/killbilling-users/8b2SQw7WRto/kaT1xxMNAgAJ).

The issue resides in the current catalog code validation. we should throw an error if any sections are missing or incorrect, such as lacking a price section.

**Comment by pierre** [comment]
I believe this should be fixed by https://github.com/killbill/killbill/issues/1481. Once implemented, we should retry to upload the _bad_ examples from the mailing-list post and verify this is indeed fixed.

**Comment by tejinderghatore** [comment]
Here is my anaylsis on this task -

1. I checked by taking the catalog xml from the mailing list https://drive.google.com/file/d/1bahqQiejj_1UNtyl9Q6bqQ7Z70JeGuXj/view and with empty prices like <prices></prices>, and I  was able to upload the catalog in the DB, without any error.

2. However, if I remove the <currency> or <value> tag inside <prices><price> tags, then I see the schema validation exception, as the xml doesn't adhere to schema validation (https://docs.killbill.io/latest/catalog.xsd), which is expected behaviour.

3. So the catalog xml is validated as per the xsd https://docs.killbill.io/latest/catalog.xsd and it wont allow the catalog xml to be added in DB, if it doesnt adhere to the xsd.

So we are good here and don't have to do anything.
